dist: xenial
cache: bundler
language: ruby
rvm:
- 2.6.1
- 2.5.3
- 2.4.5
- 2.3.8
gemfile:
- gemfiles/Gemfile.rails-5-2
- gemfiles/Gemfile.rails-5-1
- gemfiles/Gemfile.rails-5-0
- gemfiles/Gemfile.rails-4-2
jobs:
  exclude:
  - rvm: 2.6.1
    gemfile: gemfiles/Gemfile.rails-4-2
