dist: xenial
cache: bundler
language: ruby
rvm:
- 2.6.5
- 2.5.7
- 2.4.9
- 2.3.8
gemfile:
- Gemfile
- gemfiles/Gemfile.rails-6-0
- gemfiles/Gemfile.rails-5-2
- gemfiles/Gemfile.rails-5-1
- gemfiles/Gemfile.rails-5-0
- gemfiles/Gemfile.rails-4-2
jobs:
  exclude:
  - rvm: 2.3.8
    gemfile: gemfiles/Gemfile.rails-6-0
  - rvm: 2.4.9
    gemfile: gemfiles/Gemfile.rails-6-0
  - rvm: 2.6.5
    gemfile: gemfiles/Gemfile.rails-4-2
